# Generated by Django 3.0.5 on 2021-12-28 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comando',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualifica',
            field=models.CharField(choices=[('VP', 'Vigile Permanete'), ('VE', 'Vigile Esperto'), ('VC', 'Vigile Coordinatore'), ('CS', 'Capo Squadra'), ('CSE', 'Capo Squadra Esperto'), ('CR', 'Capo Reparto')], default='VP', max_length=3),
        ),
    ]
