# Generated by Django 3.0.5 on 2021-12-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211228_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile'),
        ),
    ]
