# Generated by Django 3.2.7 on 2026-03-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoHeic',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='photos/original'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file_watermark',
            field=models.FileField(upload_to='photos/watermarks/'),
        ),
    ]
