# Generated by Django 3.2.7 on 2021-10-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tweet_text', models.TextField()),
                ('retweet', models.IntegerField()),
                ('like', models.IntegerField()),
                ('url', models.CharField(max_length=250, null=True)),
                ('media_url', models.URLField(max_length=250, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
