# Generated by Django 3.0.5 on 2020-05-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('formato', models.CharField(choices=[('640', '640'), ('1280', '720'), ('1920', '1080')], default=1280, max_length=4)),
                ('posizione', models.CharField(choices=[('VERT', 'Verticale'), ('ORIZ', 'Orizzontale')], default='ORIZ', max_length=4)),
                ('codino', models.CharField(choices=[('SENZA', 'Senza'), ('CODIN', 'Codino')], default='CODIN', max_length=5)),
                ('logo', models.CharField(choices=[('SENZ', 'Senza'), ('LOGO', 'Logo')], default='LOGO', max_length=4)),
                ('video', models.FileField(default='', upload_to='video/original')),
                ('video_480', models.FileField(blank=True, null=True, upload_to='video/mp4_480')),
                ('video_720', models.FileField(blank=True, null=True, upload_to='video/mp4_720')),
            ],
        ),
    ]
