# Generated by Django 3.0.5 on 2022-01-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_480',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720',
        ),
        migrations.AddField(
            model_name='video',
            name='video_watermarks',
            field=models.FileField(blank=True, null=True, upload_to='video/watermarks'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/original'),
        ),
    ]
