# Generated by Django 3.2.7 on 2026-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20220113_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=500, upload_to='video/original'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_watermarks',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='video/watermarks'),
        ),
    ]
