# Generated by Django 3.0.5 on 2022-01-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(blank=True, default='path/to/my/default/image.jpg', upload_to='qrcode'),
        ),
    ]
