# Generated by Django 3.0.5 on 2022-01-31 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foto.Categoria')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Galleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('image', models.ImageField(blank=True, null=True, upload_to='galleria/originale')),
                ('image_thumbails', models.ImageField(blank=True, null=True, upload_to='galleria/thumbails')),
                ('image_watermarks', models.ImageField(blank=True, null=True, upload_to='galleria/watermarks')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foto.Categoria')),
            ],
            options={
                'verbose_name': 'Galleria',
                'verbose_name_plural': 'Gallerie',
            },
        ),
        migrations.CreateModel(
            name='TaggedGalleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foto.Galleria')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_taggedgalleria_items', to='taggit.Tag')),
            ],
            options={
                'ordering': ['-content_object_id'],
            },
        ),
        migrations.AddField(
            model_name='galleria',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='foto.TaggedGalleria', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='galleria',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foto.Galleria')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
