# Generated by Django 3.2.7 on 2025-12-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0002_galleria_gruppo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-id']},
        ),
    ]
